### ISSUE TITLE
(help.js) .array() is not a function.

### ISSUE THREAD

**Issue by heheleo** [imconnorngl/bot-template#3]
Hey Connor, hope your doing well.

I've had some testing with this template recently, but I've faced another error that confused me, even though the "fix" is simple.
In `help.js` line `25`, you used the function `.array()` on `bot.commands`. It does not currently work for me on Node v16. 
Litterally just says that `.array()` is not a function

Possible solution (that I am currently using):
Remove `.array()` and just keep `bot.commands`. help.js only uses some `Array` methods that are already included in Collection. 

(Too scared to open a PR, there's not much official documentation for DiscordJS's Collection, so I'm open to hear what you think of)

**Comment by imconnorngl** [comment]
Implemented a temporary fix. Will probably be upgrading the whole template to use V13 instead of the master build at some point over the coming weeks
